logger:
  level: debug
  pretty: true

database:
  database-0:
    enabled: true
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: ${POSTGRES_DOCKER_PASSWORD}
    dbname: go-kill-user
    sslmode: false

queries:
  path: ./etc/sql/

server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
